In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('^NSEBANK.csv')

In [3]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-03-01,26941.000000,30499.150391,26928.900391,30426.800781,30426.447266,0
1,2019-04-01,30537.599609,30669.800781,29435.050781,29764.800781,29764.455078,0
2,2019-05-01,29699.800781,31783.599609,28525.449219,31375.400391,31375.035156,232000
3,2019-06-01,31406.050781,31752.699219,30220.699219,31105.199219,31104.837891,274600
4,2019-07-01,31271.000000,31660.750000,28537.000000,28876.000000,28875.664063,243325800
5,2019-08-01,28660.500000,28819.699219,26560.599609,27427.849609,27427.531250,310300
6,2019-09-01,27239.199219,30801.300781,26641.349609,29103.150391,29102.812500,0
7,2019-10-01,29226.150391,30415.650391,27568.349609,30066.250000,30065.900391,1187300
8,2019-11-01,30196.150391,32157.050781,30013.650391,31946.099609,31945.728516,863100
9,2019-12-01,32008.300781,32613.099609,30996.400391,32161.650391,32161.277344,7573700
10,2020-01-01,32133.150391,32465.449219,30521.300781,30833.599609,30833.242188,6876100
11,2020-02-01,29811.750000,31649.449219,29051.500000,29147.150391,29146.812500,5445500
12,2020-03-01,29701.000000,29791.150391,16116.250000,19144.000000,19143.777344,12757800
13,2020-04-01,19122.400391,21967.000000,17143.199219,21534.500000,21534.250000,6725400
14,2020-05-01,20514.750000,20530.449219,17105.000000,19297.250000,19297.025391,7264700
15,2020-06-01,19728.900391,22479.550781,19507.050781,21370.150391,21369.902344,9626800
16,2020-07-01,21354.099609,23211.349609,21027.849609,21640.050781,21639.798828,8549900
17,2020-08-01,21543.800781,25232.599609,21031.449219,23754.349609,23754.074219,3553500
18,2020-09-01,23893.800781,24199.650391,20404.900391,21451.800781,21451.550781,245300
19,2020-10-01,21685.250000,24823.599609,21664.150391,23900.900391,23900.623047,0
20,2020-11-01,24367.599609,30197.849609,24120.599609,29609.050781,29608.707031,369400
21,2020-12-01,29844.800781,31510.250000,28976.750000,31264.050781,31263.687500,548400
22,2021-01-01,31485.150391,32842.300781,29687.699219,30565.500000,30565.144531,751600
23,2021-02-01,30976.349609,37708.750000,30906.449219,34803.601563,34803.195313,2006200
24,2021-03-01,35374.250000,36497.351563,32415.250000,33303.898438,33303.511719,374200
25,2021-04-01,33588.000000,34287.000000,30405.650391,32781.800781,32781.417969,368400
26,2021-05-01,32368.550781,35584.300781,31906.550781,35526.648438,35526.234375,1137800
27,2021-06-01,35639.750000,35810.898438,33908.949219,34772.199219,34771.796875,0
28,2021-07-01,34866.000000,35985.250000,34115.199219,34584.351563,34583.949219,329600
29,2021-08-01,34760.898438,36552.800781,34588.250000,36424.601563,36424.179688,2286900
30,2021-09-01,36591.449219,38377.250000,36151.949219,37425.101563,37424.667969,3555600
31,2021-10-01,37140.398438,41829.601563,36876.351563,39115.601563,39115.148438,5614700
32,2021-11-01,39432.148438,40160.199219,35327.898438,35695.300781,35694.886719,3582700
33,2021-12-01,35902.898438,37581.050781,34018.449219,35481.699219,35481.285156,3758900
34,2022-01-01,35585.199219,38855.550781,35526.601563,37975.351563,37974.910156,3997800
35,2022-02-01,38460.449219,39424.851563,34991.351563,36205.300781,36204.878906,4019000
36,2022-03-01,35381.898438,36827.601563,32155.349609,36373.601563,36373.179688,4358700
37,2022-04-01,36298.351563,38765.851563,35511.398438,36088.148438,36087.730469,3464000
38,2022-05-01,35627.601563,36309.300781,33001.750000,35487.398438,35486.984375,3760400
39,2022-06-01,35358.949219,35958.449219,32290.550781,33425.101563,33424.714844,2866500
40,2022-07-01,33264.750000,37754.648438,33080.449219,37491.398438,37490.960938,2908000
41,2022-08-01,37594.148438,39759.148438,37249.500000,39536.750000,39536.289063,3725600
42,2022-09-01,38806.699219,41840.148438,37386.351563,38631.949219,38631.500000,4418800
43,2022-10-01,38444.898438,41530.648438,37963.250000,41307.898438,41307.417969,4021900
44,2022-11-01,41552.398438,43339.148438,40819.148438,43231.000000,43230.496094,5445800
45,2022-12-01,43512.101563,44151.800781,41597.648438,42986.449219,42985.949219,6044400
46,2023-01-01,43038.250000,43578.398438,39419.800781,40655.050781,40654.578125,1802430600
47,2023-02-01,41115.000000,42015.648438,39490.500000,40269.050781,40269.050781,3825600
48,2023-03-01,40473.851563,41671.199219,38613.148438,40608.648438,40608.648438,3574400
49,2023-04-01,40695.800781,43302.050781,40535.898438,43233.898438,43233.898438,3289200
50,2023-05-01,43395.050781,44498.601563,42582.199219,44128.148438,44128.148438,4286800
51,2023-06-01,44172.050781,44787.101563,43345.949219,44747.351563,44747.351563,3530500
52,2023-07-01,44957.949219,46369.500000,44547.800781,45651.101563,45651.101563,5599800
53,2023-08-01,45740.000000,45782.750000,43600.351563,43989.148438,43989.148438,4576300
54,2023-09-01,43996.101563,46310.398438,43830.750000,44584.550781,44584.550781,5017400
55,2023-10-01,44561.500000,44710.550781,42105.398438,42845.949219,42845.949219,3781300
56,2023-11-01,42694.250000,44764.800781,42589.648438,44481.750000,44481.750000,3067400
57,2023-12-01,44580.148438,48636.449219,44531.750000,48292.250000,48292.250000,4418700
58,2024-01-01,48194.800781,48381.949219,44429.000000,45996.800781,45996.800781,5217800
59,2024-02-01,46164.898438,46892.351563,44633.851563,46384.851563,46384.851563,3330600

In [9]:
df['Daily returns'] = df['Close']/df['Open'] - 1

In [10]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily returns
0,2019-03-01,26941.000000,30499.150391,26928.900391,30426.800781,30426.447266,0,0.129386
1,2019-04-01,30537.599609,30669.800781,29435.050781,29764.800781,29764.455078,0,-0.025306
2,2019-05-01,29699.800781,31783.599609,28525.449219,31375.400391,31375.035156,232000,0.056418
3,2019-06-01,31406.050781,31752.699219,30220.699219,31105.199219,31104.837891,274600,-0.009579
4,2019-07-01,31271.000000,31660.750000,28537.000000,28876.000000,28875.664063,243325800,-0.076589
5,2019-08-01,28660.500000,28819.699219,26560.599609,27427.849609,27427.531250,310300,-0.043009
6,2019-09-01,27239.199219,30801.300781,26641.349609,29103.150391,29102.812500,0,0.068429
7,2019-10-01,29226.150391,30415.650391,27568.349609,30066.250000,30065.900391,1187300,0.028745
8,2019-11-01,30196.150391,32157.050781,30013.650391,31946.099609,31945.728516,863100,0.057953
9,2019-12-01,32008.300781,32613.099609,30996.400391,32161.650391,32161.277344,7573700,0.004791
10,2020-01-01,32133.150391,32465.449219,30521.300781,30833.599609,30833.242188,6876100,-0.040443
11,2020-02-01,29811.750000,31649.449219,29051.500000,29147.150391,29146.812500,5445500,-0.022293
12,2020-03-01,29701.000000,29791.150391,16116.250000,19144.000000,19143.777344,12757800,-0.355443
13,2020-04-01,19122.400391,21967.000000,17143.199219,21534.500000,21534.250000,6725400,0.126140
14,2020-05-01,20514.750000,20530.449219,17105.000000,19297.250000,19297.025391,7264700,-0.059348
15,2020-06-01,19728.900391,22479.550781,19507.050781,21370.150391,21369.902344,9626800,0.083190
16,2020-07-01,21354.099609,23211.349609,21027.849609,21640.050781,21639.798828,8549900,0.013391
17,2020-08-01,21543.800781,25232.599609,21031.449219,23754.349609,23754.074219,3553500,0.102607
18,2020-09-01,23893.800781,24199.650391,20404.900391,21451.800781,21451.550781,245300,-0.102202
19,2020-10-01,21685.250000,24823.599609,21664.150391,23900.900391,23900.623047,0,0.102173
20,2020-11-01,24367.599609,30197.849609,24120.599609,29609.050781,29608.707031,369400,0.215099
21,2020-12-01,29844.800781,31510.250000,28976.750000,31264.050781,31263.687500,548400,0.047554
22,2021-01-01,31485.150391,32842.300781,29687.699219,30565.500000,30565.144531,751600,-0.029209
23,2021-02-01,30976.349609,37708.750000,30906.449219,34803.601563,34803.195313,2006200,0.123554
24,2021-03-01,35374.250000,36497.351563,32415.250000,33303.898438,33303.511719,374200,-0.058527
25,2021-04-01,33588.000000,34287.000000,30405.650391,32781.800781,32781.417969,368400,-0.024003
26,2021-05-01,32368.550781,35584.300781,31906.550781,35526.648438,35526.234375,1137800,0.097567
27,2021-06-01,35639.750000,35810.898438,33908.949219,34772.199219,34771.796875,0,-0.024342
28,2021-07-01,34866.000000,35985.250000,34115.199219,34584.351563,34583.949219,329600,-0.008078
29,2021-08-01,34760.898438,36552.800781,34588.250000,36424.601563,36424.179688,2286900,0.047861
30,2021-09-01,36591.449219,38377.250000,36151.949219,37425.101563,37424.667969,3555600,0.022783
31,2021-10-01,37140.398438,41829.601563,36876.351563,39115.601563,39115.148438,5614700,0.053182
32,2021-11-01,39432.148438,40160.199219,35327.898438,35695.300781,35694.886719,3582700,-0.094767
33,2021-12-01,35902.898438,37581.050781,34018.449219,35481.699219,35481.285156,3758900,-0.011732
34,2022-01-01,35585.199219,38855.550781,35526.601563,37975.351563,37974.910156,3997800,0.067167
35,2022-02-01,38460.449219,39424.851563,34991.351563,36205.300781,36204.878906,4019000,-0.058636
36,2022-03-01,35381.898438,36827.601563,32155.349609,36373.601563,36373.179688,4358700,0.028029
37,2022-04-01,36298.351563,38765.851563,35511.398438,36088.148438,36087.730469,3464000,-0.005791
38,2022-05-01,35627.601563,36309.300781,33001.750000,35487.398438,35486.984375,3760400,-0.003935
39,2022-06-01,35358.949219,35958.449219,32290.550781,33425.101563,33424.714844,2866500,-0.054692
40,2022-07-01,33264.750000,37754.648438,33080.449219,37491.398438,37490.960938,2908000,0.127061
41,2022-08-01,37594.148438,39759.148438,37249.500000,39536.750000,39536.289063,3725600,0.051673
42,2022-09-01,38806.699219,41840.148438,37386.351563,38631.949219,38631.500000,4418800,-0.004503
43,2022-10-01,38444.898438,41530.648438,37963.250000,41307.898438,41307.417969,4021900,0.074470
44,2022-11-01,41552.398438,43339.148438,40819.148438,43231.000000,43230.496094,5445800,0.040397
45,2022-12-01,43512.101563,44151.800781,41597.648438,42986.449219,42985.949219,6044400,-0.012081
46,2023-01-01,43038.250000,43578.398438,39419.800781,40655.050781,40654.578125,1802430600,-0.055374
47,2023-02-01,41115.000000,42015.648438,39490.500000,40269.050781,40269.050781,3825600,-0.020575
48,2023-03-01,40473.851563,41671.199219,38613.148438,40608.648438,40608.648438,3574400,0.003330
49,2023-04-01,40695.800781,43302.050781,40535.898438,43233.898438,43233.898438,3289200,0.062368
50,2023-05-01,43395.050781,44498.601563,42582.199219,44128.148438,44128.148438,4286800,0.016894
51,2023-06-01,44172.050781,44787.101563,43345.949219,44747.351563,44747.351563,3530500,0.013024
52,2023-07-01,44957.949219,46369.500000,44547.800781,45651.101563,45651.101563,5599800,0.015418
53,2023-08-01,45740.000000,45782.750000,43600.351563,43989.148438,43989.148438,4576300,-0.038278
54,2023-09-01,43996.101563,46310.398438,43830.750000,44584.550781,44584.550781,5017400,0.013375
55,2023-10-01,44561.500000,44710.550781,42105.398438,42845.949219,42845.949219,3781300,-0.038498
56,2023-11-01,42694.250000,44764.800781,42589.648438,44481.750000,44481.750000,3067400,0.041867
57,2023-12-01,44580.148438,48636.449219,44531.750000,48292.250000,48292.250000,4418700,0.083268
58,2024-01-01,48194.800781,48381.949219,44429.000000,45996.800781,45996.800781,5217800,-0.045607
59,2024-02-01,46164.898438,46892.351563,44633.851563,46384.851563,46384.851563,3330600,0.004765

In [11]:
import numpy as np

In [12]:
cov = np.cov(df)

TypeError: can only concatenate str (not "float") to str

In [13]:
df1 = pd.read_csv('^NSEBANK1.csv')

In [14]:
df1

,Date,Open,High,Low,Close,Adj Close,Volume
0,2023-02-20,41221.550781,41292.601563,40580.101563,40701.699219,40701.699219,143700.0
1,2023-02-21,40784.898438,40946.199219,40508.250000,40673.601563,40673.601563,170200.0
2,2023-02-22,40494.148438,40529.250000,39899.000000,39995.898438,39995.898438,155200.0
3,2023-02-23,39983.699219,40147.800781,39600.250000,40001.550781,40001.550781,200500.0
4,2023-02-24,40259.101563,40348.101563,39818.898438,39909.398438,39909.398438,144600.0
...,...,...,...,...,...,...,...
240,2024-02-13,45056.800781,45750.398438,44819.550781,45502.398438,45502.398438,245900.0
241,2024-02-14,45014.648438,46170.449219,44860.750000,45908.300781,45908.300781,280000.0
242,2024-02-15,46027.101563,46297.699219,45590.199219,46218.898438,46218.898438,277700.0
243,2024-02-16,46454.300781,46693.398438,46264.398438,46384.851563,46384.851563,291400.0
244,2024-02-19,46454.300781,46717.398438,46317.699219,46662.101563,46662.101563,0.0

In [15]:
df1['Daily returns'] = df1['Close']/df1['Open'] - 1

In [16]:
df1

,Date,Open,High,Low,Close,Adj Close,Volume,Daily returns
0,2023-02-20,41221.550781,41292.601563,40580.101563,40701.699219,40701.699219,143700.0,-0.012611
1,2023-02-21,40784.898438,40946.199219,40508.250000,40673.601563,40673.601563,170200.0,-0.002729
2,2023-02-22,40494.148438,40529.250000,39899.000000,39995.898438,39995.898438,155200.0,-0.012304
3,2023-02-23,39983.699219,40147.800781,39600.250000,40001.550781,40001.550781,200500.0,0.000446
4,2023-02-24,40259.101563,40348.101563,39818.898438,39909.398438,39909.398438,144600.0,-0.008686
...,...,...,...,...,...,...,...,...
240,2024-02-13,45056.800781,45750.398438,44819.550781,45502.398438,45502.398438,245900.0,0.009890
241,2024-02-14,45014.648438,46170.449219,44860.750000,45908.300781,45908.300781,280000.0,0.019852
242,2024-02-15,46027.101563,46297.699219,45590.199219,46218.898438,46218.898438,277700.0,0.004167
243,2024-02-16,46454.300781,46693.398438,46264.398438,46384.851563,46384.851563,291400.0,-0.001495
244,2024-02-19,46454.300781,46717.398438,46317.699219,46662.101563,46662.101563,0.0,0.004473

In [18]:
A = df['Daily returns'].cov(df1['Daily returns'])

In [19]:
A

3.539992208922979e-05

In [23]:
variance = df1['Daily returns'].var()

In [24]:
variance

4.885647734937866e-05

In [25]:
beta = A/variance

In [26]:
beta

0.7245696785726201

In [27]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily returns
0,2019-03-01,26941.000000,30499.150391,26928.900391,30426.800781,30426.447266,0,0.129386
1,2019-04-01,30537.599609,30669.800781,29435.050781,29764.800781,29764.455078,0,-0.025306
2,2019-05-01,29699.800781,31783.599609,28525.449219,31375.400391,31375.035156,232000,0.056418
3,2019-06-01,31406.050781,31752.699219,30220.699219,31105.199219,31104.837891,274600,-0.009579
4,2019-07-01,31271.000000,31660.750000,28537.000000,28876.000000,28875.664063,243325800,-0.076589
5,2019-08-01,28660.500000,28819.699219,26560.599609,27427.849609,27427.531250,310300,-0.043009
6,2019-09-01,27239.199219,30801.300781,26641.349609,29103.150391,29102.812500,0,0.068429
7,2019-10-01,29226.150391,30415.650391,27568.349609,30066.250000,30065.900391,1187300,0.028745
8,2019-11-01,30196.150391,32157.050781,30013.650391,31946.099609,31945.728516,863100,0.057953
9,2019-12-01,32008.300781,32613.099609,30996.400391,32161.650391,32161.277344,7573700,0.004791
10,2020-01-01,32133.150391,32465.449219,30521.300781,30833.599609,30833.242188,6876100,-0.040443
11,2020-02-01,29811.750000,31649.449219,29051.500000,29147.150391,29146.812500,5445500,-0.022293
12,2020-03-01,29701.000000,29791.150391,16116.250000,19144.000000,19143.777344,12757800,-0.355443
13,2020-04-01,19122.400391,21967.000000,17143.199219,21534.500000,21534.250000,6725400,0.126140
14,2020-05-01,20514.750000,20530.449219,17105.000000,19297.250000,19297.025391,7264700,-0.059348
15,2020-06-01,19728.900391,22479.550781,19507.050781,21370.150391,21369.902344,9626800,0.083190
16,2020-07-01,21354.099609,23211.349609,21027.849609,21640.050781,21639.798828,8549900,0.013391
17,2020-08-01,21543.800781,25232.599609,21031.449219,23754.349609,23754.074219,3553500,0.102607
18,2020-09-01,23893.800781,24199.650391,20404.900391,21451.800781,21451.550781,245300,-0.102202
19,2020-10-01,21685.250000,24823.599609,21664.150391,23900.900391,23900.623047,0,0.102173
20,2020-11-01,24367.599609,30197.849609,24120.599609,29609.050781,29608.707031,369400,0.215099
21,2020-12-01,29844.800781,31510.250000,28976.750000,31264.050781,31263.687500,548400,0.047554
22,2021-01-01,31485.150391,32842.300781,29687.699219,30565.500000,30565.144531,751600,-0.029209
23,2021-02-01,30976.349609,37708.750000,30906.449219,34803.601563,34803.195313,2006200,0.123554
24,2021-03-01,35374.250000,36497.351563,32415.250000,33303.898438,33303.511719,374200,-0.058527
25,2021-04-01,33588.000000,34287.000000,30405.650391,32781.800781,32781.417969,368400,-0.024003
26,2021-05-01,32368.550781,35584.300781,31906.550781,35526.648438,35526.234375,1137800,0.097567
27,2021-06-01,35639.750000,35810.898438,33908.949219,34772.199219,34771.796875,0,-0.024342
28,2021-07-01,34866.000000,35985.250000,34115.199219,34584.351563,34583.949219,329600,-0.008078
29,2021-08-01,34760.898438,36552.800781,34588.250000,36424.601563,36424.179688,2286900,0.047861
30,2021-09-01,36591.449219,38377.250000,36151.949219,37425.101563,37424.667969,3555600,0.022783
31,2021-10-01,37140.398438,41829.601563,36876.351563,39115.601563,39115.148438,5614700,0.053182
32,2021-11-01,39432.148438,40160.199219,35327.898438,35695.300781,35694.886719,3582700,-0.094767
33,2021-12-01,35902.898438,37581.050781,34018.449219,35481.699219,35481.285156,3758900,-0.011732
34,2022-01-01,35585.199219,38855.550781,35526.601563,37975.351563,37974.910156,3997800,0.067167
35,2022-02-01,38460.449219,39424.851563,34991.351563,36205.300781,36204.878906,4019000,-0.058636
36,2022-03-01,35381.898438,36827.601563,32155.349609,36373.601563,36373.179688,4358700,0.028029
37,2022-04-01,36298.351563,38765.851563,35511.398438,36088.148438,36087.730469,3464000,-0.005791
38,2022-05-01,35627.601563,36309.300781,33001.750000,35487.398438,35486.984375,3760400,-0.003935
39,2022-06-01,35358.949219,35958.449219,32290.550781,33425.101563,33424.714844,2866500,-0.054692
40,2022-07-01,33264.750000,37754.648438,33080.449219,37491.398438,37490.960938,2908000,0.127061
41,2022-08-01,37594.148438,39759.148438,37249.500000,39536.750000,39536.289063,3725600,0.051673
42,2022-09-01,38806.699219,41840.148438,37386.351563,38631.949219,38631.500000,4418800,-0.004503
43,2022-10-01,38444.898438,41530.648438,37963.250000,41307.898438,41307.417969,4021900,0.074470
44,2022-11-01,41552.398438,43339.148438,40819.148438,43231.000000,43230.496094,5445800,0.040397
45,2022-12-01,43512.101563,44151.800781,41597.648438,42986.449219,42985.949219,6044400,-0.012081
46,2023-01-01,43038.250000,43578.398438,39419.800781,40655.050781,40654.578125,1802430600,-0.055374
47,2023-02-01,41115.000000,42015.648438,39490.500000,40269.050781,40269.050781,3825600,-0.020575
48,2023-03-01,40473.851563,41671.199219,38613.148438,40608.648438,40608.648438,3574400,0.003330
49,2023-04-01,40695.800781,43302.050781,40535.898438,43233.898438,43233.898438,3289200,0.062368
50,2023-05-01,43395.050781,44498.601563,42582.199219,44128.148438,44128.148438,4286800,0.016894
51,2023-06-01,44172.050781,44787.101563,43345.949219,44747.351563,44747.351563,3530500,0.013024
52,2023-07-01,44957.949219,46369.500000,44547.800781,45651.101563,45651.101563,5599800,0.015418
53,2023-08-01,45740.000000,45782.750000,43600.351563,43989.148438,43989.148438,4576300,-0.038278
54,2023-09-01,43996.101563,46310.398438,43830.750000,44584.550781,44584.550781,5017400,0.013375
55,2023-10-01,44561.500000,44710.550781,42105.398438,42845.949219,42845.949219,3781300,-0.038498
56,2023-11-01,42694.250000,44764.800781,42589.648438,44481.750000,44481.750000,3067400,0.041867
57,2023-12-01,44580.148438,48636.449219,44531.750000,48292.250000,48292.250000,4418700,0.083268
58,2024-01-01,48194.800781,48381.949219,44429.000000,45996.800781,45996.800781,5217800,-0.045607
59,2024-02-01,46164.898438,46892.351563,44633.851563,46384.851563,46384.851563,3330600,0.004765

In [48]:
x = df.loc[df['Date']=='2024-02-01']

In [42]:
y = df.loc[df['Date']=='2023-02-01']

In [66]:
x

,Date,Open,High,Low,Close,Adj Close,Volume,Daily returns
59,2024-02-01,46164.898438,46892.351563,44633.851563,46384.851563,46384.851563,3330600,0.004765

In [68]:
ret = 0.15187348

In [69]:
rf = 0.0711

In [71]:
ROE = rf + beta*(ret-rf)

In [72]:
ROE

0.12962601444079197